using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FormulaCalculator
{
    public static class Calculator
    {
        //decimal offical documentation: https://learn.microsoft.com/en-us/dotnet/api/system.decimal?view=net-7.0

        public static decimal Sum(decimal a, decimal b)
        {
            //Copy code from the first calulator assignment
            throw new NotImplementedException();
        }

        public static decimal Divide(decimal a, decimal b)
        {
            //Copy code from the first calulator assignment
            throw new NotImplementedException();
        }

        public static decimal Multiply(decimal a, decimal b)
        {
            //Copy code from the first calulator assignment
            throw new NotImplementedException();
        }

        public static decimal Subtract(decimal a, decimal b)
        {
            //Copy code from the first calulator assignment
            throw new NotImplementedException();
        }

        public static decimal CalculateFormula(string formula)
        {
            //Assignment: Return the result of calculating the formula passed in.  The formula will be in the format of 1 + 2 or 1 - 2 etc (only two numbers!).  You need to parse the formula and call the appropriate method.

            //If you get CalculateFormula_ValidFormulas_ReturnsExpectedResult test to pass you will get 50% on this assignment.
            //If you get CalculateFormula_InvalidFormulas_ThrowsException also to pass you will get 100% on this assignment.
            //Also if you get 50% of both test methods test to pass you get 50% on this assignment.
            
            //For CalculateFormula_InvalidFormulas_ThrowsException to get to pass you need throw correct exception in different situations (e.g. divide by zero)
            //Look CalculateFormula_InvalidFormulas_ThrowsException test cases for examples in what cases an exception is expected

            throw new NotImplementedException();
        }
    }
}
